In [1]:
import pandas as pd

In [2]:
data_file = "Resources/livwell_lin_interpolated.csv"
data_file_df = pd.read_csv(data_file)
data_file_df

,country_name,country_code,year,region_num_harmonized,region_name_harmonized,SurveyId,interview_year_mean,interview_month_mean,CMC_interview_mean,DM_age_15.19_p,...,EI_computer_p,EI_computer_p_se,DP_decide_no_contraception_p,DP_decide_no_contraception_p_se,EI_internet_day_p,EI_internet_day_p_se,EI_internet_week_p,EI_internet_week_p_se,EI_mobile_p,EI_mobile_p_se
0,Colombia,COL,1990,1,Atlantica,CO1990DHS,1990.0,7.0,1086.75,21.52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Colombia,COL,1990,2,Oriental,CO1990DHS,1990.0,7.0,1086.93,22.84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Colombia,COL,1990,3,Central,CO1990DHS,1990.0,7.0,1086.76,19.49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Colombia,COL,1990,4,Pacifica,CO1990DHS,1990.0,7.0,1086.59,21.86,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Colombia,COL,1990,5,Bogota,CO1990DHS,1990.0,5.0,1085.41,19.51,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7365,Senegal,SEN,2019,4,Kolda + Ziguinchor + Sedhiou (South),SN2019DHS,2019.0,8.0,1435.61,24.41,...,10.67,2.09,76.89,2.18,13.12,1.77,23.30,2.13,55.54,2.54
7366,Sierra Leone,SLE,2019,1,Eastern,SL2019DHS,2019.0,7.0,1434.66,21.11,...,2.06,0.34,44.78,2.50,3.01,0.50,5.56,0.62,33.34,1.65
7367,Sierra Leone,SLE,2019,2,Northern + North Western,SL2019DHS,2019.0,7.0,1434.77,22.77,...,2.36,0.30,52.67,2.31,3.43,0.41,5.44,0.54,34.53,1.36
7368,Sierra Leone,SLE,2019,3,Southern,SL2019DHS,2019.0,7.0,1434.62,21.73,...,2.33,0.36,63.38,2.04,5.50,0.50,7.19,0.66,32.44,1.54
7369,Sierra Leone,SLE,2019,4,Western,SL2019DHS,2019.0,6.0,1434.14,21.76,...,14.71,1.37,48.40,3.45,20.95,1.68,30.15,1.96,70.46,1.44

In [3]:
repro_health_df = data_file_df.loc[:, data_file_df.columns.str.startswith('RH_')]
repro_health_df.columns

Index(['RH_age_first_birth_mean', 'RH_age_first_birth_mean_se',
       'RH_age_first_sex_mean', 'RH_age_first_sex_mean_se',
       'RH_children_born_mean', 'RH_children_born_mean_se',
       'RH_children_living_mean', 'RH_children_living_mean_se',
       'RH_contr_modern_know_p', 'RH_contr_modern_know_p_se',
       'RH_contr_modern_p', 'RH_contr_modern_p_se', 'RH_contr_p',
       'RH_contr_p_se', 'RH_family_planning_mobile_p',
       'RH_family_planning_mobile_p_se', 'RH_family_planning_radio_p',
       'RH_family_planning_radio_p_se', 'RH_family_planning_tv_p',
       'RH_family_planning_tv_p_se', 'RH_family_planning_news_p',
       'RH_family_planning_news_p_se'],
      dtype='object')

In [4]:
repro_health_df = data_file_df[['RH_age_first_birth_mean', 'RH_age_first_birth_mean_se',
       'RH_age_first_sex_mean', 'RH_age_first_sex_mean_se',
       'RH_children_born_mean', 'RH_children_born_mean_se',
       'RH_children_living_mean', 'RH_children_living_mean_se',
       'RH_contr_modern_know_p', 'RH_contr_modern_know_p_se',
       'RH_contr_modern_p', 'RH_contr_modern_p_se', 'RH_contr_p',
       'RH_contr_p_se', 'RH_family_planning_mobile_p',
       'RH_family_planning_mobile_p_se', 'RH_family_planning_radio_p',
       'RH_family_planning_radio_p_se', 'RH_family_planning_tv_p',
       'RH_family_planning_tv_p_se', 'RH_family_planning_news_p',
       'RH_family_planning_news_p_se','country_name']]
repro_health_df.set_index('country_name', inplace=True)
repro_health_df

,RH_age_first_birth_mean,RH_age_first_birth_mean_se,RH_age_first_sex_mean,RH_age_first_sex_mean_se,RH_children_born_mean,RH_children_born_mean_se,RH_children_living_mean,RH_children_living_mean_se,RH_contr_modern_know_p,RH_contr_modern_know_p_se,...,RH_contr_p,RH_contr_p_se,RH_family_planning_mobile_p,RH_family_planning_mobile_p_se,RH_family_planning_radio_p,RH_family_planning_radio_p_se,RH_family_planning_tv_p,RH_family_planning_tv_p_se,RH_family_planning_news_p,RH_family_planning_news_p_se
country_name,,,,,,,,,,,,,,,,,,,,,
Colombia,20.48,0.15,18.53,0.16,2.24,0.08,2.12,0.07,99.57,0.15,...,33.98,1.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Colombia,21.52,0.28,19.93,0.25,2.19,0.14,2.05,0.12,95.05,1.17,...,43.64,2.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Colombia,21.20,0.18,19.42,0.16,1.96,0.12,1.81,0.10,98.43,0.55,...,39.37,1.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Colombia,21.26,0.28,19.24,0.30,1.90,0.13,1.78,0.12,98.37,0.58,...,39.36,1.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Colombia,22.22,0.17,20.14,0.18,1.50,0.05,1.45,0.05,98.90,0.25,...,45.29,1.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Senegal,19.74,0.16,17.46,0.17,2.68,0.09,2.38,0.08,95.57,0.94,...,23.24,1.42,1.01,0.26,49.74,2.01,32.28,1.89,7.86,0.85
Sierra Leone,19.16,0.13,15.40,0.07,2.92,0.07,2.40,0.05,98.85,0.21,...,25.35,1.15,1.74,0.30,22.54,1.42,2.27,0.45,0.59,0.15
Sierra Leone,19.51,0.11,15.59,0.10,2.68,0.04,2.28,0.04,97.34,0.37,...,22.15,0.90,4.17,0.72,26.43,2.49,6.17,0.81,1.24,0.25
Sierra Leone,19.44,0.13,16.03,0.12,2.92,0.07,2.47,0.05,93.89,0.74,...,26.09,1.17,1.73,0.42,16.72,1.37,2.58,0.52,0.54,0.14
Sierra Leone,19.78,0.14,16.29,0.10,1.79,0.05,1.54,0.04,99.18,0.31,...,25.25,1.16,10.85,1.21,50.27,2.47,32.42,2.30,6.81,0.86

In [5]:
fertility_df = data_file_df.loc[:, data_file_df.columns.str.startswith('FF_')]
fertility_df.columns

Index(['FF_ASFR_15.19', 'FF_ASFR_20.24', 'FF_ASFR_25.29', 'FF_ASFR_30.34',
       'FF_ASFR_35.39', 'FF_ASFR_40.44', 'FF_ASFR_45.49', 'FF_ASFR_SE_15.19',
       'FF_ASFR_SE_20.24', 'FF_ASFR_SE_25.29', 'FF_ASFR_SE_30.34',
       'FF_ASFR_SE_35.39', 'FF_ASFR_SE_40.44', 'FF_ASFR_SE_45.49', 'FF_GFR',
       'FF_GFR_SE', 'FF_TFR', 'FF_TFR_SE'],
      dtype='object')

In [6]:
fertility_df = data_file_df[['FF_ASFR_15.19', 'FF_ASFR_20.24', 'FF_ASFR_25.29', 'FF_ASFR_30.34',
       'FF_ASFR_35.39', 'FF_ASFR_40.44', 'FF_ASFR_45.49', 'FF_ASFR_SE_15.19',
       'FF_ASFR_SE_20.24', 'FF_ASFR_SE_25.29', 'FF_ASFR_SE_30.34',
       'FF_ASFR_SE_35.39', 'FF_ASFR_SE_40.44', 'FF_ASFR_SE_45.49', 'FF_GFR',
       'FF_GFR_SE', 'FF_TFR', 'FF_TFR_SE','country_name']]
fertility_df.set_index('country_name', inplace=True)
fertility_df

,FF_ASFR_15.19,FF_ASFR_20.24,FF_ASFR_25.29,FF_ASFR_30.34,FF_ASFR_35.39,FF_ASFR_40.44,FF_ASFR_45.49,FF_ASFR_SE_15.19,FF_ASFR_SE_20.24,FF_ASFR_SE_25.29,FF_ASFR_SE_30.34,FF_ASFR_SE_35.39,FF_ASFR_SE_40.44,FF_ASFR_SE_45.49,FF_GFR,FF_GFR_SE,FF_TFR,FF_TFR_SE
country_name,,,,,,,,,,,,,,,,,,
Colombia,89.525,195.969,180.204,134.492,68.256,33.357,13.182,9.476,13.969,16.834,14.617,11.906,12.897,9.245,133.119,6.579,3.575,0.234
Colombia,47.245,204.926,147.721,65.814,79.380,5.271,0.000,9.408,24.012,17.481,13.817,15.224,3.431,0.000,102.954,9.280,2.752,0.203
Colombia,61.827,150.545,126.903,84.533,59.855,21.929,3.553,10.549,16.208,13.279,13.522,12.519,16.944,3.074,93.763,6.754,2.546,0.176
Colombia,100.075,165.222,142.106,95.463,49.402,14.769,0.000,17.573,27.121,17.021,20.778,12.694,9.779,0.000,105.669,9.245,2.835,0.219
Colombia,42.887,121.272,147.191,104.688,57.607,15.665,0.000,8.022,10.928,12.821,13.680,11.080,6.804,0.000,90.598,4.668,2.447,0.138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Senegal,106.033,219.916,242.824,214.255,165.200,66.024,49.333,10.581,17.321,15.583,17.505,21.162,15.549,17.773,177.298,8.092,5.318,0.357
Sierra Leone,112.600,227.526,205.471,180.421,117.896,56.217,29.622,10.423,11.039,9.931,10.782,10.286,8.126,9.234,156.711,4.191,4.649,0.161
Sierra Leone,108.894,206.340,190.118,170.187,133.487,55.198,27.755,5.436,6.961,12.128,7.999,7.452,5.960,6.354,151.306,4.158,4.460,0.139
Sierra Leone,133.052,235.986,221.269,191.893,118.942,78.480,14.398,8.933,9.853,12.170,9.872,8.068,10.715,6.285,169.922,5.019,4.970,0.202
Sierra Leone,60.004,146.192,153.616,115.702,91.796,15.332,3.542,6.759,8.903,10.536,10.963,12.244,6.484,3.525,108.282,4.068,2.931,0.123

In [7]:
child_mort_df = data_file_df[["HL_IMR","HL_CMR","HL_U5MR","HL_NNMR","HL_PNNMR","country_name"]]
child_mort_df.columns

Index(['HL_IMR', 'HL_CMR', 'HL_U5MR', 'HL_NNMR', 'HL_PNNMR', 'country_name'], dtype='object')

In [8]:
child_mort_df

      HL_IMR  HL_CMR  HL_U5MR  HL_NNMR  HL_PNNMR  country_name
0      19.51    9.52    28.85    11.98      7.53      Colombia
1      13.25    7.99    21.13    10.86      2.38      Colombia
2      15.86    4.99    20.77    10.26      5.60      Colombia
3      17.50    2.43    19.88     6.74     10.76      Colombia
4      15.58    4.85    20.36    10.47      5.11      Colombia
...      ...     ...      ...      ...       ...           ...
7365   40.53   20.26    59.97    23.32     17.21       Senegal
7366   73.30   47.66   117.47    31.35     41.95  Sierra Leone
7367   79.71   53.59   129.02    31.95     47.76  Sierra Leone
7368   78.89   46.11   121.36    23.42     55.47  Sierra Leone
7369   64.80   51.92   113.35    34.96     29.84  Sierra Leone

[7370 rows x 6 columns]

In [9]:
dom_vio_df = data_file_df.loc[:, data_file_df.columns.str.startswith('DV_')]
dom_vio_df.columns

Index(['DV_phys_12m_p', 'DV_phys_12m_p_se', 'DV_phys_or_sex_partner_12m_p',
       'DV_phys_or_sex_partner_12m_p_se', 'DV_phys_or_sex_partner_p',
       'DV_phys_or_sex_partner_p_se', 'DV_phys_p', 'DV_phys_p_se',
       'DV_phys_partner_12m_p', 'DV_phys_partner_12m_p_se',
       'DV_phys_partner_p', 'DV_phys_partner_p_se', 'DV_sex_12m_p',
       'DV_sex_12m_p_se', 'DV_sex_p', 'DV_sex_p_se', 'DV_sex_partner_12m_p',
       'DV_sex_partner_12m_p_se', 'DV_sex_partner_p', 'DV_sex_partner_p_se'],
      dtype='object')

In [10]:
dom_vio_df = data_file_df[['DV_phys_12m_p', 'DV_phys_12m_p_se', 'DV_phys_or_sex_partner_12m_p',
       'DV_phys_or_sex_partner_12m_p_se', 'DV_phys_or_sex_partner_p',
       'DV_phys_or_sex_partner_p_se', 'DV_phys_p', 'DV_phys_p_se',
       'DV_phys_partner_12m_p', 'DV_phys_partner_12m_p_se',
       'DV_phys_partner_p', 'DV_phys_partner_p_se', 'DV_sex_12m_p',
       'DV_sex_12m_p_se', 'DV_sex_p', 'DV_sex_p_se', 'DV_sex_partner_12m_p',
       'DV_sex_partner_12m_p_se', 'DV_sex_partner_p', 'DV_sex_partner_p_se','country_name']]
dom_vio_df.set_index('country_name', inplace=True)
dom_vio_df

,DV_phys_12m_p,DV_phys_12m_p_se,DV_phys_or_sex_partner_12m_p,DV_phys_or_sex_partner_12m_p_se,DV_phys_or_sex_partner_p,DV_phys_or_sex_partner_p_se,DV_phys_p,DV_phys_p_se,DV_phys_partner_12m_p,DV_phys_partner_12m_p_se,DV_phys_partner_p,DV_phys_partner_p_se,DV_sex_12m_p,DV_sex_12m_p_se,DV_sex_p,DV_sex_p_se,DV_sex_partner_12m_p,DV_sex_partner_12m_p_se,DV_sex_partner_p,DV_sex_partner_p_se
country_name,,,,,,,,,,,,,,,,,,,,
Colombia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Colombia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Colombia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Colombia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Colombia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Senegal,7.44,1.38,6.55,1.53,21.19,3.13,29.13,2.76,5.76,1.31,20.40,3.03,2.04,0.95,2.10,0.95,1.40,0.93,2.41,1.30
Sierra Leone,38.27,2.63,28.42,1.93,38.76,1.96,63.45,3.08,27.42,1.89,38.01,1.96,2.46,0.52,4.49,0.72,2.83,0.57,4.40,0.78
Sierra Leone,45.10,1.99,46.65,1.96,59.93,1.94,60.22,1.84,44.57,2.03,56.98,1.85,5.74,0.75,9.25,0.87,7.60,1.00,9.82,1.01
Sierra Leone,37.84,1.75,29.17,1.86,40.98,2.04,59.62,2.08,29.01,1.87,40.89,2.04,2.23,0.44,4.14,0.60,2.83,0.59,3.27,0.67
Sierra Leone,47.44,3.03,48.89,3.83,59.51,3.34,59.73,3.14,46.25,3.64,56.90,3.21,6.04,1.38,9.75,1.78,10.34,2.28,13.74,2.42

In [11]:
energy_df = data_file_df.loc[:, data_file_df.columns.str.startswith('EI_')]
energy_df.columns

Index(['EI_elec_p', 'EI_elec_p_se', 'EI_fridge_p', 'EI_fridge_p_se',
       'EI_radio_p', 'EI_radio_p_se', 'EI_tv_p', 'EI_tv_p_se',
       'EI_women_elec_p', 'EI_women_elec_p_se', 'EI_women_fridge_p',
       'EI_women_fridge_p_se', 'EI_women_radio_p', 'EI_women_radio_p_se',
       'EI_women_tv_p', 'EI_women_tv_p_se', 'EI_telephone_p',
       'EI_telephone_p_se', 'EI_women_telephone_p', 'EI_women_telephone_p_se',
       'EI_modern_cooking_p', 'EI_modern_cooking_p_se', 'EI_news_week_p',
       'EI_news_week_p_se', 'EI_radio_week_p', 'EI_radio_week_p_se',
       'EI_tv_week_p', 'EI_tv_week_p_se', 'EI_women_modern_cooking_p',
       'EI_women_modern_cooking_p_se', 'EI_computer_p', 'EI_computer_p_se',
       'EI_internet_day_p', 'EI_internet_day_p_se', 'EI_internet_week_p',
       'EI_internet_week_p_se', 'EI_mobile_p', 'EI_mobile_p_se'],
      dtype='object')

In [12]:
energy_df = data_file_df[['EI_elec_p', 'EI_elec_p_se', 'EI_fridge_p', 'EI_fridge_p_se',
       'EI_radio_p', 'EI_radio_p_se', 'EI_tv_p', 'EI_tv_p_se',
       'EI_women_elec_p', 'EI_women_elec_p_se', 'EI_women_fridge_p',
       'EI_women_fridge_p_se', 'EI_women_radio_p', 'EI_women_radio_p_se',
       'EI_women_tv_p', 'EI_women_tv_p_se', 'EI_telephone_p',
       'EI_telephone_p_se', 'EI_women_telephone_p', 'EI_women_telephone_p_se',
       'EI_modern_cooking_p', 'EI_modern_cooking_p_se', 'EI_news_week_p',
       'EI_news_week_p_se', 'EI_radio_week_p', 'EI_radio_week_p_se',
       'EI_tv_week_p', 'EI_tv_week_p_se', 'EI_women_modern_cooking_p',
       'EI_women_modern_cooking_p_se', 'EI_computer_p', 'EI_computer_p_se',
       'EI_internet_day_p', 'EI_internet_day_p_se', 'EI_internet_week_p',
       'EI_internet_week_p_se', 'EI_mobile_p', 'EI_mobile_p_se','country_name']]
energy_df.set_index('country_name', inplace=True)
energy_df

,EI_elec_p,EI_elec_p_se,EI_fridge_p,EI_fridge_p_se,EI_radio_p,EI_radio_p_se,EI_tv_p,EI_tv_p_se,EI_women_elec_p,EI_women_elec_p_se,...,EI_women_modern_cooking_p,EI_women_modern_cooking_p_se,EI_computer_p,EI_computer_p_se,EI_internet_day_p,EI_internet_day_p_se,EI_internet_week_p,EI_internet_week_p_se,EI_mobile_p,EI_mobile_p_se
country_name,,,,,,,,,,,,,,,,,,,,,
Colombia,80.97,2.83,43.21,2.08,66.81,1.95,59.02,2.23,85.80,2.46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Colombia,89.03,2.50,44.44,4.16,85.50,2.08,59.93,4.10,91.19,1.96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Colombia,89.46,3.34,55.95,2.60,86.35,1.29,73.91,2.40,93.06,2.01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Colombia,90.98,1.69,51.08,3.58,85.94,1.47,72.12,2.78,92.93,1.40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Colombia,99.56,0.19,65.02,2.35,95.80,0.62,92.78,0.79,99.75,0.16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Senegal,47.90,4.05,17.05,2.06,55.88,2.11,40.74,3.12,49.21,4.58,...,4.20,0.87,10.67,2.09,13.12,1.77,23.30,2.13,55.54,2.54
Sierra Leone,9.82,1.59,4.43,0.91,51.16,1.62,8.08,1.42,13.17,1.99,...,0.02,0.02,2.06,0.34,3.01,0.50,5.56,0.62,33.34,1.65
Sierra Leone,11.33,1.10,5.09,0.54,48.20,1.25,9.89,0.77,12.19,1.28,...,0.12,0.05,2.36,0.30,3.43,0.41,5.44,0.54,34.53,1.36
Sierra Leone,7.47,0.83,4.34,0.51,51.73,1.50,7.52,0.76,10.75,1.31,...,0.16,0.10,2.33,0.36,5.50,0.50,7.19,0.66,32.44,1.54
Sierra Leone,64.24,2.88,36.75,2.23,72.43,1.59,58.55,2.67,66.16,3.32,...,1.64,0.45,14.71,1.37,20.95,1.68,30.15,1.96,70.46,1.44

In [13]:
energy_avg = energy_df[['EI_elec_p', 'EI_elec_p_se', 'EI_fridge_p', 'EI_fridge_p_se',
       'EI_radio_p', 'EI_radio_p_se', 'EI_tv_p', 'EI_tv_p_se',
       'EI_women_elec_p', 'EI_women_elec_p_se', 'EI_women_fridge_p',
       'EI_women_fridge_p_se', 'EI_women_radio_p', 'EI_women_radio_p_se',
       'EI_women_tv_p', 'EI_women_tv_p_se', 'EI_telephone_p',
       'EI_telephone_p_se', 'EI_women_telephone_p', 'EI_women_telephone_p_se',
       'EI_modern_cooking_p', 'EI_modern_cooking_p_se', 'EI_news_week_p',
       'EI_news_week_p_se', 'EI_radio_week_p', 'EI_radio_week_p_se',
       'EI_tv_week_p', 'EI_tv_week_p_se', 'EI_women_modern_cooking_p',
       'EI_women_modern_cooking_p_se', 'EI_computer_p', 'EI_computer_p_se',
       'EI_internet_day_p', 'EI_internet_day_p_se', 'EI_internet_week_p',
       'EI_internet_week_p_se', 'EI_mobile_p', 'EI_mobile_p_se']].mean(axis=1)

In [14]:
energy_avg

country_name
Colombia        34.265625
Colombia        38.005625
Colombia        40.874375
Colombia        39.861250
Colombia        45.146875
                  ...
Senegal         15.115526
Sierra Leone     6.508684
Sierra Leone     6.668684
Sierra Leone     6.475000
Sierra Leone    19.305263
Length: 7370, dtype: float64

In [15]:
df = data_file_df[['EI_elec_p', 'EI_elec_p_se', 'EI_fridge_p', 'EI_fridge_p_se',
       'EI_radio_p', 'EI_radio_p_se', 'EI_tv_p', 'EI_tv_p_se',
       'EI_women_elec_p', 'EI_women_elec_p_se', 'EI_women_fridge_p',
       'EI_women_fridge_p_se', 'EI_women_radio_p', 'EI_women_radio_p_se',
       'EI_women_tv_p', 'EI_women_tv_p_se', 'EI_telephone_p',
       'EI_telephone_p_se', 'EI_women_telephone_p', 'EI_women_telephone_p_se',
       'EI_modern_cooking_p', 'EI_modern_cooking_p_se', 'EI_news_week_p',
       'EI_news_week_p_se', 'EI_radio_week_p', 'EI_radio_week_p_se',
       'EI_tv_week_p', 'EI_tv_week_p_se', 'EI_women_modern_cooking_p',
       'EI_women_modern_cooking_p_se', 'EI_computer_p', 'EI_computer_p_se',
       'EI_internet_day_p', 'EI_internet_day_p_se', 'EI_internet_week_p',
       'EI_internet_week_p_se', 'EI_mobile_p', 'EI_mobile_p_se',
                   'country_name', 
                   'DV_phys_12m_p', 'DV_phys_12m_p_se', 'DV_phys_or_sex_partner_12m_p',
       'DV_phys_or_sex_partner_12m_p_se', 'DV_phys_or_sex_partner_p',
       'DV_phys_or_sex_partner_p_se', 'DV_phys_p', 'DV_phys_p_se',
       'DV_phys_partner_12m_p', 'DV_phys_partner_12m_p_se',
       'DV_phys_partner_p', 'DV_phys_partner_p_se', 'DV_sex_12m_p',
       'DV_sex_12m_p_se', 'DV_sex_p', 'DV_sex_p_se', 'DV_sex_partner_12m_p',
       'DV_sex_partner_12m_p_se', 'DV_sex_partner_p', 'DV_sex_partner_p_se', 
                   "HL_IMR","HL_CMR","HL_U5MR","HL_NNMR","HL_PNNMR",
                   'FF_ASFR_15.19', 'FF_ASFR_20.24', 'FF_ASFR_25.29', 'FF_ASFR_30.34',
       'FF_ASFR_35.39', 'FF_ASFR_40.44', 'FF_ASFR_45.49', 'FF_ASFR_SE_15.19',
       'FF_ASFR_SE_20.24', 'FF_ASFR_SE_25.29', 'FF_ASFR_SE_30.34',
       'FF_ASFR_SE_35.39', 'FF_ASFR_SE_40.44', 'FF_ASFR_SE_45.49', 'FF_GFR',
        'FF_GFR_SE', 'FF_TFR', 'FF_TFR_SE',
                   'RH_age_first_birth_mean', 'RH_age_first_birth_mean_se',
       'RH_age_first_sex_mean', 'RH_age_first_sex_mean_se',
       'RH_children_born_mean', 'RH_children_born_mean_se',
       'RH_children_living_mean', 'RH_children_living_mean_se',
       'RH_contr_modern_know_p', 'RH_contr_modern_know_p_se',
       'RH_contr_modern_p', 'RH_contr_modern_p_se', 'RH_contr_p',
       'RH_contr_p_se', 'RH_family_planning_mobile_p',
       'RH_family_planning_mobile_p_se', 'RH_family_planning_radio_p',
       'RH_family_planning_radio_p_se', 'RH_family_planning_tv_p',
       'RH_family_planning_tv_p_se', 'RH_family_planning_news_p',
       'RH_family_planning_news_p_se']]

In [16]:
df

,EI_elec_p,EI_elec_p_se,EI_fridge_p,EI_fridge_p_se,EI_radio_p,EI_radio_p_se,EI_tv_p,EI_tv_p_se,EI_women_elec_p,EI_women_elec_p_se,...,RH_contr_p,RH_contr_p_se,RH_family_planning_mobile_p,RH_family_planning_mobile_p_se,RH_family_planning_radio_p,RH_family_planning_radio_p_se,RH_family_planning_tv_p,RH_family_planning_tv_p_se,RH_family_planning_news_p,RH_family_planning_news_p_se
0,80.97,2.83,43.21,2.08,66.81,1.95,59.02,2.23,85.80,2.46,...,33.98,1.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,89.03,2.50,44.44,4.16,85.50,2.08,59.93,4.10,91.19,1.96,...,43.64,2.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,89.46,3.34,55.95,2.60,86.35,1.29,73.91,2.40,93.06,2.01,...,39.37,1.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,90.98,1.69,51.08,3.58,85.94,1.47,72.12,2.78,92.93,1.40,...,39.36,1.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,99.56,0.19,65.02,2.35,95.80,0.62,92.78,0.79,99.75,0.16,...,45.29,1.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7365,47.90,4.05,17.05,2.06,55.88,2.11,40.74,3.12,49.21,4.58,...,23.24,1.42,1.01,0.26,49.74,2.01,32.28,1.89,7.86,0.85
7366,9.82,1.59,4.43,0.91,51.16,1.62,8.08,1.42,13.17,1.99,...,25.35,1.15,1.74,0.30,22.54,1.42,2.27,0.45,0.59,0.15
7367,11.33,1.10,5.09,0.54,48.20,1.25,9.89,0.77,12.19,1.28,...,22.15,0.90,4.17,0.72,26.43,2.49,6.17,0.81,1.24,0.25
7368,7.47,0.83,4.34,0.51,51.73,1.50,7.52,0.76,10.75,1.31,...,26.09,1.17,1.73,0.42,16.72,1.37,2.58,0.52,0.54,0.14
7369,64.24,2.88,36.75,2.23,72.43,1.59,58.55,2.67,66.16,3.32,...,25.25,1.16,10.85,1.21,50.27,2.47,32.42,2.30,6.81,0.86

In [17]:
df.count()

EI_elec_p                        7188
EI_elec_p_se                     7188
EI_fridge_p                      7164
EI_fridge_p_se                   7164
EI_radio_p                       7315
                                 ...
RH_family_planning_radio_p_se    6658
RH_family_planning_tv_p          6610
RH_family_planning_tv_p_se       6658
RH_family_planning_news_p        6391
RH_family_planning_news_p_se     6439
Length: 104, dtype: int64

In [18]:
df=df.dropna(how="any")
df.count()

EI_elec_p                        158
EI_elec_p_se                     158
EI_fridge_p                      158
EI_fridge_p_se                   158
EI_radio_p                       158
                                ...
RH_family_planning_radio_p_se    158
RH_family_planning_tv_p          158
RH_family_planning_tv_p_se       158
RH_family_planning_news_p        158
RH_family_planning_news_p_se     158
Length: 104, dtype: int64

In [19]:
df.set_index('country_name', inplace=True)

In [20]:
df

,EI_elec_p,EI_elec_p_se,EI_fridge_p,EI_fridge_p_se,EI_radio_p,EI_radio_p_se,EI_tv_p,EI_tv_p_se,EI_women_elec_p,EI_women_elec_p_se,...,RH_contr_p,RH_contr_p_se,RH_family_planning_mobile_p,RH_family_planning_mobile_p_se,RH_family_planning_radio_p,RH_family_planning_radio_p_se,RH_family_planning_tv_p,RH_family_planning_tv_p_se,RH_family_planning_news_p,RH_family_planning_news_p_se
country_name,,,,,,,,,,,,,,,,,,,,,
Malawi,12.48,1.27,6.91,1.21,44.61,1.25,16.03,1.24,14.54,1.38,...,44.55,1.15,7.87,0.74,49.38,1.61,16.57,1.03,15.30,1.29
Malawi,8.87,1.11,6.08,1.04,39.21,0.84,10.43,0.97,11.96,1.60,...,48.66,0.83,5.78,0.51,42.67,1.01,9.73,0.98,9.48,0.78
Malawi,12.01,0.79,5.79,0.47,40.76,0.72,11.77,0.69,14.93,0.96,...,43.76,0.63,4.37,0.30,37.12,0.85,10.13,0.62,8.52,0.43
Zimbabwe,18.53,2.67,11.56,1.61,39.88,2.20,23.67,2.13,20.63,3.10,...,43.30,2.20,6.27,0.89,27.35,2.00,10.42,1.30,13.11,1.26
Zimbabwe,12.28,2.63,8.16,1.46,47.06,2.44,22.86,2.70,14.49,3.16,...,53.27,2.05,6.68,1.16,30.54,2.20,9.51,1.17,12.35,1.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Senegal,47.90,4.05,17.05,2.06,55.88,2.11,40.74,3.12,49.21,4.58,...,23.24,1.42,1.01,0.26,49.74,2.01,32.28,1.89,7.86,0.85
Sierra Leone,9.82,1.59,4.43,0.91,51.16,1.62,8.08,1.42,13.17,1.99,...,25.35,1.15,1.74,0.30,22.54,1.42,2.27,0.45,0.59,0.15
Sierra Leone,11.33,1.10,5.09,0.54,48.20,1.25,9.89,0.77,12.19,1.28,...,22.15,0.90,4.17,0.72,26.43,2.49,6.17,0.81,1.24,0.25
Sierra Leone,7.47,0.83,4.34,0.51,51.73,1.50,7.52,0.76,10.75,1.31,...,26.09,1.17,1.73,0.42,16.72,1.37,2.58,0.52,0.54,0.14
Sierra Leone,64.24,2.88,36.75,2.23,72.43,1.59,58.55,2.67,66.16,3.32,...,25.25,1.16,10.85,1.21,50.27,2.47,32.42,2.30,6.81,0.86